package design

import (
	_ "algtmapi/design/resources/search"
	"algtmapi/env"

	. "github.com/goadesign/goa/design"
	. "github.com/goadesign/goa/design/apidsl"
)

var _ = API("algtmapi", func() {
	Title("algtmapi")
	Description("aikatsup proxy for Aikatsu☆LGTM")
	Version("1.0")
	Contact(func() {
		Name("romiogaku")
		Email("romiogaku@me.com")
	})
	Host(env.Server.APIHostStringOnDoc())
	Scheme("http")
	BasePath("/api")
	Consumes("application/json") // Media types supported by the API
	Produces("application/json") // Media types generated by the API
})
